version: '3.7'

services:
  haproxy-proxy-balancer:
    build:
      context: ../proxy-balancer
      dockerfile: Dockerfile
    container_name: haproxy-proxy-balancer
    hostname: haproxy-pb
    volumes:
      - ../proxy-balancer/haproxy:/usr/local/etc/haproxy/
    restart: always
    depends_on:
      wgcf1:
        condition: service_healthy
      wgcf2:
        condition: service_healthy
      # dante_1:
      #   condition: service_started
      # dante_2:
      #   condition: service_started
    networks:
      - freedium_net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1080" ]
      interval: 5s
      # interval: 120s
      timeout: 15s
      retries: 3
