services:
  haproxy-proxy-balancer:
    profiles:
      - prod
    build:
      context: ../proxy-balancer
      dockerfile: Dockerfile
    container_name: haproxy-proxy-balancer
    hostname: haproxy-pb
    volumes:
      - ../proxy-balancer/haproxy:/usr/local/etc/haproxy/
    restart: always
    depends_on:
      wgcf1:
        condition: service_healthy
      #wgcf2:
      #  condition: service_healthy
      #wgcf3:
      #  condition: service_healthy
      #wgcf4:
      #  condition: service_healthy
    networks:
      - freedium_net
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "1080" ]
      interval: 5s
      # interval: 120s
      timeout: 15s
      retries: 3
