# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-toml
      # - id: check-json
      - id: check-xml
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: bash -c 'cd freedium-library && pdm run pytest'
  #       language: system
  #       types: [python]
  #       pass_filenames: false
  #       always_run: true
  #       verbose: true
